#!/usr/bin/env ruby

# Behind firewall in Windows environs that blocks git protocol so I have to use http
protocol = RUBY_PLATFORM =~ /(win|w)32$/ ? 'https' : 'git'

git_bundles = [
  "#{protocol}://github.com/vim-scripts/L9.git",
  "#{protocol}://github.com/vim-scripts/FuzzyFinder.git",
  "#{protocol}://github.com/scrooloose/nerdcommenter.git",
  "#{protocol}://github.com/msanders/snipmate.vim.git",
  "#{protocol}://github.com/tpope/vim-cucumber.git",
  "#{protocol}://github.com/tpope/vim-haml.git",
  "#{protocol}://github.com/tpope/vim-rails.git",
  "#{protocol}://github.com/tpope/vim-surround.git",
  "#{protocol}://github.com/edsono/vim-matchit.git",
  "#{protocol}://github.com/ecomba/vim-ruby-refactoring.git",
  "#{protocol}://github.com/bronson/vim-ruby-block-conv.git",
  "#{protocol}://github.com/altercation/vim-colors-solarized.git",
  "#{protocol}://github.com/godlygeek/csapprox.git",
  "#{protocol}://github.com/kchmck/vim-coffee-script.git",
  "#{protocol}://github.com/vim-scripts/AutoTag.git",
  "#{protocol}://github.com/tpope/vim-bundler.git",
  "#{protocol}://github.com/tpope/vim-rake.git",
  "#{protocol}://github.com/tpope/vim-rails.git",
  "#{protocol}://github.com/tpope/vim-ragtag.git"
]

vim_org_scripts = []

require 'fileutils'
require 'open-uri'

bundles_dir = File.expand_path(File.dirname(__FILE__), "bundle")

FileUtils.cd(bundles_dir)

trash = ARGV.include?('--trash')

if trash
  puts "Trashing everything (lookout!)"
  Dir["*"].each {|d| FileUtils.rm_rf d }
end

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  if !trash && File.exists?(dir)
    puts "  Skipping #{dir}"
    next
  end
  puts "  Unpacking #{url} into #{dir}"
  `git clone #{url} #{dir}`
  FileUtils.rm_rf(File.join(dir, ".git"))
end

vim_org_scripts.each do |name, script_id, script_type|
  local_file = File.join(name, script_type, "#{name}.#{script_type == 'zip' ? 'zip' : 'vim'}")
  if !trash && File.exists?(local_file)
    puts "  Skipping #{local_file}"
    next
  end
  puts " Downloading #{name}"
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
  if script_type == 'zip'
    %x(unzip -d #{name} #{local_file})
  end
end
